### ISSUE TITLE
When executing a single expression tool, bunny fails with docker error

### ISSUE THREAD

**Issue by StarvingMarvin** [rabix/bunny#109]
Trying to run this tool from command line:

```yaml
class: ExpressionTool
cwlVersion: v1.0
requirements:
  InlineJavascriptRequirement: {}
inputs:
  in: string
outputs:
  out: string
expression: "$({out: inputs.in})"

```

Produces the following error log: 
[error.log.txt](https://github.com/rabix/bunny/files/729726/error.log.txt)
