### ISSUE TITLE
CWL inputBinding bug for arrays

### ISSUE THREAD

**Issue by adamstruck** [rabix/bunny#218]
If there is an input binding set on the items of an array input, but not the input itself the resulting command is not constructed properly. 

Example below:

```
cwlVersion: v1.0
class: CommandLineTool

baseCommand: 
  - someCommand

inputs:
  test:
    type: 
      - type: array
        items: File
        inputBinding:
          prefix: -f

outputs:
   output:
    type: stdout
```

Produces the command `someCommand` when it should produce `someCommand -f file1 -f file2`

To get bunny to output the desired command I had to rewrite the CWL like this:

```
cwlVersion: v1.0
class: CommandLineTool

baseCommand: 
  - someCommand

inputs:
  test:
    type: 
      - type: array
        items: File
        inputBinding:
          prefix: -f
    inputBinding:
      position: 0

outputs:
   output:
    type: stdout
```
