### ISSUE TITLE
Type replacement triggered on arbitrary nodes

### ISSUE THREAD

**Issue by milos-ljubinkovic** [rabix/bunny#317]
If any node in a cwl file, not just step or root, has "inputs" as a subnode, type replacement in [CWLDocumentResolver](https://github.com/rabix/bunny/blob/5894f858522156764223dbccb859b40b14f4ff81/rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/resolver/CWLDocumentResolver.java#L286) is triggered and an exception is thrown if replacement fails.

Example wf (courtesy of @ivanbatic ):

```
class: CommandLineTool
cwlVersion: v1.0
baseCommand:
  - cat
  - example.conf
inputs:
  - id: message
    type: string
    secondaryFiles: []
outputs: []
requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entryname: example.conf
        entry: |
          CONFIGVAR=$(inputs.message)
'sbg:job1':
  inputs:
    message: message-string-value
  runtime:
    cores: 1
    ram: 1000

```

This check for inputs should be more precise or replacement should be changed.
