### ISSUE TITLE
ResourceRequirements not passed to TES backend

### ISSUE THREAD

**Issue by adamstruck** [rabix/bunny#422]
CWL snippet: 
```
cwlVersion: v1.0
class: CommandLineTool
id: bwa_mem
requirements:
  - class: DockerRequirement
    dockerPull: 'kfdrc/bwa-picard:broad'
  - class: ShellCommandRequirement
  - class: InlineJavascriptRequirement
  - class: ResourceRequirement
    ramMin: 14000
    coresMin: 16
baseCommand: [java, -Xms5000m, -jar, /picard.jar]
```

The call to [getRequirements](https://github.com/rabix/bunny/blob/master/rabix-backend-tes/src/main/java/org/rabix/backend/tes/service/impl/LocalTESWorkerServiceImpl.java#L397-L402) returns an array with the ResourceRequirement mapped to the `CustomRequirement` class.
