### ISSUE TITLE
Tool default files are relative to input file rather then workflow file

### ISSUE THREAD

**Issue by kellrott** [rabix/bunny#71]
Default files referenced from the workflow seem to be found relative to the input file rather then the workflow file. The reference implementation does to opposite. Because the workflows and input files are in the same folder in the conformance test, this behavior probably isn't noticed in testing.

Example workflow (in the same directory put a README.md file)
```
class: CommandLineTool
cwlVersion: v1.0
hints:
  DockerRequirement:
    dockerPull: ubuntu

baseCommand: [md5sum]
inputs:
  script:
    type: File
    default:
      class: File
      location: README.md
    inputBinding:
      position: 1

stdout: out.txt

outputs:
  checksum:
    type: File
    outputBinding:
      glob: out.txt
```

Create an empty dictionary file named `empty_input.json`
If `empty_input.json` is in the same directory as the workflow, the command 
`java -jar rabix/lib/rabix-backend-local.jar default_file.cwl empty_input.json` will work.
But if it is move to `tmp/empty_input.json` then the command `java -jar rabix/lib/rabix-backend-local.jar default_file.cwl tmp/empty_input.json` will fail because 
```
$ cat tmp/4983a396-9289-41c9-996b-9c0f4c8e516b/root/job.err.log
md5sum: /Users/ellrott/workspaces/gaea-bmeg/tmp/README.md: No such file or directory
```
