### ISSUE TITLE
Trying to run a basic workflow, getting "Error reading the app file"

### ISSUE THREAD

**Issue by prismofeverything** [rabix/bunny#91]
This may just be user error, but I am not sure how to debug this or proceed. 

I ran rabix with the `-v` flag and this is the extent of the output:

```
/Users/spanglry/Code/rabix/rabix -v /Users/spanglry/Code/gaia-bmeg/agent/hugo/hugo-gz.cwl.yaml /Users/spanglry/Code/gaia-bmeg/work/agent_workflow__DoQxB.json
[2016-12-20 10:41:21.820] [DEBUG] [main] o.r.b.l.BackendCommandLine [BackendCommandLine.java:377] Config path: /Users/spanglry/Code/rabix/config
[2016-12-20 10:41:21.825] [DEBUG] [main] o.r.b.l.BackendCommandLine [BackendCommandLine.java:379] Configuration directory found localy.
Error reading the app file
```

Here is the workflow:

```
cwlVersion: v1.0
class: Workflow

inputs:
    hgnc_file:
        type: File
        #dirac:sourceUrl: ftp://ftp.ebi.ac.uk/pub/databases/genenames/hgnc_complete_set.txt.gz

steps:
    unzip:
      run:
        class: CommandLineTool
        hints:
          DockerRequirement:
            dockerPull: bmeg/bmeg-python
        baseCommand: [gunzip, -c]
        inputs:
          gz:
            type: File
            inputBinding:
              position: 1
        outputs:
          out:
              type: File
              outputBinding:
                glob: out.txt
        stdout: out.txt
      in:
        gz: hgnc_file
      out:
        - out
    convert:
      run:
        class: CommandLineTool
        hints:
          DockerRequirement:
            dockerPull: bmeg/bmeg-python
        baseCommand: [python]
        inputs:
          script:
            type: File
            default:
              class: File
              location: convert-hugo.py
            inputBinding: 
              position: 1
          hugoFile:
            type: File
            inputBinding:
              prefix: "--hugo"
              position: 2
          outname:
            type: string
            default: out.json
            inputBinding:
              prefix: "--out"
              position: 3
        outputs:
          proto:
            type: File
            outputBinding:
              glob: out.json
      in:
        hugoFile: unzip/out
      out: 
        - proto

outputs:
  proto: 
    type: File
    outputSource: "convert/proto"
```

And here is the input file:

```
{"hgnc_file": {"path": "/Users/spanglry/Code/gaia-bmeg/scripts/../cache/b21fc277d723d86aeef54677674783cc", "class": "File"}}
```

I have verified the input file exists, and I have also successfully run this exact workflow using `cwltool` (replacing `rabix` with `cwltool`).

Questions: what does the term `app file` refer to? How do I specify an `app file` and how do I pass it into the program? Or is there some other issue at work here?

Thanks for taking a look!
